source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "rubydb", path: "../../../"
gem "rubydb-activerecord", path: "../../../adapters/activerecord"

gem "tzinfo-data", platforms: %i[windows jruby]
